version: '3.8'

services:
  # PHP-FPM (Laravel)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-api-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  # Servidor Nginx
  webserver:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

networks:
  laravel_network:
